name: Feature Request
description: Suggest an idea for Worther
title: '[FEATURE] '
labels: ['Feature']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature for Worther!

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: dropdown
    id: weather-data-type
    attributes:
      label: Type of Weather Data
      description: What type of weather data would this feature involve?
      multiple: true
      options:
        - Historical Data
        - Current Conditions
        - Forecasts
        - Alerts
        - Maps
        - Charts/Visualizations
        - Other
    validations:
      required: false

  - type: input
    id: target-location
    attributes:
      label: Target Location Feature
      description: What location functionality would this feature involve?
      placeholder: e.g. Multiple Cities, Specific Region, Global view
    validations:
      required: false

  - type: dropdown
    id: update-frequency
    attributes:
      label: Update Frequency
      description: How often should this feature update data?
      options:
        - Real-time
        - Every few minutes
        - Hourly
        - Daily
        - On-demand only
        - Other
    validations:
      required: false

  - type: textarea
    id: user-benefits
    attributes:
      label: User Benefits
      description: Explain how this feature would benefit users of the weather website.
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request here.
    validations:
      required: false
