name: Auto Approve Dependabot PRs

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  pull-requests: write

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Approve PR and add comment
        run: |
          gh pr review --approve "$PR_URL"
          gh pr comment "$PR_URL" --body "Dependabot has been detected, PR auto-approved"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
