name: Auto Approve PRs

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
  issue_comment:
    types:
      - created

permissions:
  pull-requests: write
  issues: write
  contents: read

jobs:
  auto-approve-dependabot:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]'
    steps:
      - name: Approve PR and add comment
        run: |
          gh pr review --approve "${{ github.event.pull_request.number }}"
          gh pr comment "${{ github.event.pull_request.number }}" --body "Dependabot has been detected, PR auto-approved"
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  approve-from-comment:
    runs-on: ubuntu-latest
    if: github.event_name == 'issue_comment' && contains(github.event.issue.html_url, '/pull/') && contains(github.event.comment.body, '!approve')
    steps:
      - name: Check if comment author is repository owner
        id: check-author
        run: |
          AUTHOR="${{ github.event.comment.user.login }}"
          # Use built-in context variable for repository owner
          REPO_OWNER="${{ github.repository_owner }}"
          if [[ "$AUTHOR" == "$REPO_OWNER" ]]; then
            echo "is_authorized=true" >> $GITHUB_OUTPUT
          else
            echo "is_authorized=false" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve PR from comment
        if: steps.check-author.outputs.is_authorized == 'true'
        run: |
          gh pr review "${{ github.event.issue.number }}" --approve
          gh pr comment "${{ github.event.issue.number }}" --body "PR approved by repository owner via comment"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
