name: Changelog Checker

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - 'resources/CHANGELOG.md'

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for changelog changes
        id: changelog-check
        run: |
          git fetch origin ${{ github.base_ref }}
          CHANGELOG_CHANGED=$(git diff --name-only origin/${{ github.base_ref }} | grep -c "resources/CHANGELOG.md" || true)
          echo "changed=$CHANGELOG_CHANGED" >> $GITHUB_OUTPUT

      - name: Handle changelog status
        run: |
          if [[ ${{ steps.changelog-check.outputs.changed }} == "0" ]]; then
            echo "No changelog changes detected"
            gh pr edit ${{ github.event.pull_request.number }} --add-label "Changelog needed"
            exit 1
          else
            echo "Changelog changes detected"
            gh pr edit ${{ github.event.pull_request.number }} --remove-label "Changelog needed"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
