name: PR Labeller

on:
  pull_request:
    types: [opened, edited]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Label PR based on template
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const prBody = context.payload.pull_request.body;
            const labels = [];
            
            const labelMappings = {
              'Bug fix': 'Bug',
              'New feature': 'Feature',
              'UI/UX improvement': 'UI/UX',
              'Weather data processing': 'Data Processing',
              'Optimisation': 'Optimisation',
              'Documentation update': 'Documentation'
            };
            
            for (const [text, label] of Object.entries(labelMappings)) {
              if (prBody && prBody.includes(`- [x] ${text}`)) {
                labels.push(label);
              }
            }
            
            if (labels.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: labels
              });
            }
